### ISSUE TITLE
Support signed ssh server keys

### ISSUE THREAD

**Issue by TimJDFletcher** [kryptco/ssh-wire#5]
I have been testing Krypton on my mac to compare it with ssh keys stored on a Yubikey.

One issue that I have run into is signed ssh server keys. I use these for secure automation with ansible, basically allowing removing the TOFU problem for automation pipelines.

When I login to a host with a signed server key the iOS app prompts me to allow access to an unknown host, if I disable the signed server key the app correctly prompts me with the system name.

From `ssh -v` the difference seems to be in these lines:

Prompts for unknown host
```
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256-cert-v01@openssh.com
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host certificate: ecdsa-sha2-nistp256-cert-v01@openssh.com 
```
Prompts correctly for the system name:
```
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
```

**Comment by kcking** [comment]
Hi Tim, thank you for reaching out about this. We do not yet support verifying host certificates. 

Krypton Teams currently provides a way to pin individual host public keys for your team, and we may add support for adding trusted HostCAs to your team in the future.

**Comment by TimJDFletcher** [comment]
Hi, I might not have been clear about the actual issue. The problem is that the iOS app doesn't show the hostname at all even if the host's key is already know, it is always unknown host if the server provides a signed key.
